### PR TITLE
FOGL-8538: Upgrade S2OPC Toolkit to version 1.5.0

### PR DESCRIPTION
**Pull request by RVerhoeff**
Update the S2OPCUA South plugin to use _[S2OPC Toolkit 1.5.0](https://gitlab.com/systerel/S2OPC/-/releases/S2OPC_Toolkit_1.5.0)_.

This Pull Request depends on the Fledge [Pull Request #1415](https://github.com/fledge-iot/fledge/pull/1415) which adds new file utilities to Fledge.

### CODE REVIEW

**Comment by ashish-jabble** [comment]
Hi @RVerhoeff CI checker is failing which is expected as it compiles with default develop core branch and you mentioned that this PR depends upon Core branch `FOGL-8538A`. Therefore to build compile with custom core branch I have pushed another branch on top of your's i.e FOGL-8538B but now its compilation is still failing.

Last stack trace lines are given below
```
12:14:55  CMakeFiles/RunTests.dir/home/ubuntu/workspace/_fledge-south-s2opcua_FOGL-8538B/opcua.cpp.o: In function `OPCUA::start()':
12:14:55  opcua.cpp:(.text+0x9d5d): undefined reference to `copyFile(char const*, char const*)'
12:14:55  opcua.cpp:(.text+0x9fb3): undefined reference to `copyFile(char const*, char const*)'
12:14:55  opcua.cpp:(.text+0xa3c1): undefined reference to `copyFile(char const*, char const*)'
12:14:55  collect2: error: ld returned 1 exit status
```
Here is the [detailed console logs](http://jenkins.dianomic.com:8080/job/fledge-iot-plugins-tester/job/fledge-south-s2opcua/job/FOGL-8538B/1/console).
Machine details: Ubuntu18.04 with amd64/x86_64 architecture  on which Plugin PR tester is running.

Once the compilation issue is fixed we need to update the same changes on centralized packaging repo.

**Comment by RVerhoeff** [comment]
@ashish-jabble , the compilation error (_undefined reference to `copyFile'_) is a direct result of [FOGL-8538A](https://github.com/fledge-iot/fledge/pull/1415) not yet being merged into the Fledge repository. Routine _copyFile_ was introduced in that branch. Mark approved FOGL-8538A and I have merged it into develop.

**Comment by ashish-jabble** [comment]
@RVerhoeff I have retriggered the Job and now its compilation is okay and checker is pas on CI. Now the only change left in packaging repo.

**Comment by ashish-jabble** [comment]
@RVerhoeff I see this branch has 4 commits ahead and 10 commits behind than develop.
Please update the branch with develop.

**Comment by RVerhoeff** [comment]
@ashish-jabble , I merged the FOGL-8538 branch into develop today. When you wrote that this branch was 4 commits ahead of develop and 10 commits behind, I believe you were referring to your FOGL-8538B branch. Do we need to do new work on that branch at all? I think that was just your attempt to solve the missing _file_utils_ problem.

**Comment by ashish-jabble** [comment]
> When you wrote that this branch was 4 commits ahead of develop and 10 commits behind, I believe you were referring to your FOGL-8538B branch

@RVerhoeff No, I mean only the original branch i.e FOGL-8538. Last commit of this branch `d419df3` and it's behind with develop as the its package related VERSION points to `2.3.0`. When I made the package against this branch before merge it's with 2.3.0 version. I have just only asked to merge or rebase your branch with develop. Anyway now you have merged into develop so no further action required!

For the package related changes, we usually check the Plugin health with  on-demand packaging to verify the changes. Because there may have some chances to add extra things in case of packaging other than dev things.
Anyway, now I will be triggering the packages with develop branch of this plugin and with s2opcua common additional package changes at https://github.com/fledge-iot/fledge-pkg/pull/94. And then check the plugin discovery for all supported platforms.

> Do we need to do new work on that branch at all?

Nope

**Pull request merged**
